#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const OUTPUT = path.join(ROOT, 'INDEX.md');
const EXCLUDE_DIRS = new Set(['node_modules', '.git', '.agent', 'tmp', 'backup']);

const FILE_CATEGORIES = [
  { prefix: 'src/', label: 'src/' },
  { prefix: 'lib/', label: 'lib/' },
  { prefix: 'handlers/', label: 'handlers/' },
  { prefix: 'services/', label: 'services/' },
  { prefix: 'scripts/', label: 'scripts/' },
  { prefix: 'db/', label: 'db/' },
];

function categorizeFile(relPath) {
  for (const cat of FILE_CATEGORIES) {
    if (relPath.startsWith(cat.prefix)) return cat.label;
  }
  return 'root';
}

function scanFiles(dir) {
  const results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.isDirectory()) {
      if (EXCLUDE_DIRS.has(entry.name)) continue;
      results.push(...scanFiles(path.join(dir, entry.name)));
    } else if (entry.isFile() && /\.(js|ts|gs)$/i.test(entry.name)) {
      results.push(path.join(dir, entry.name));
    }
  }
  return results;
}

function extractFunctions(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const lines = content.split('\n');
  const functions = [];
  const patterns = [
    /^\s*function\s+(\w+)\s*\(/,
    /^\s*(?:const|let|var)\s+(\w+)\s*=\s*(?:\(|[\w]+\s*=>|function\s*\()/,
    /^\s*(\w+)\s*:\s*(?:\(|async\s*\(|function\s*\()/,
    /^\s*(?:app|router)\.(\w+(?:\.\w+)*)\s*=\s*(?:\(|async\s*\(|function\s*\()/,
  ];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.includes('||') && line.includes('?')) continue;
    if (/=\s*\(/.test(line) && !/=>/.test(line) && !/function/.test(line)) continue;
    if (/getElementById|querySelector|appendChild|createElement/.test(line)) continue;
    if (line.trimStart().startsWith('//') || line.trimStart().startsWith('*')) continue;

    for (const pattern of patterns) {
      const match = line.match(pattern);
      if (match) {
        const name = match[1];
        if (name && name.length > 1 && !/^(if|for|while|switch|catch|return|case|else)$/.test(name)) {
          const afterName = line.substring(line.indexOf(name) + name.length).trim();
          if (afterName.startsWith('=')) {
            const afterEq = afterName.substring(1).trim();
            if (!afterEq.startsWith('(') && !afterEq.startsWith('function') && !afterEq.includes('=>')) continue;
          }
          if (!afterName.startsWith(':') && !afterName.startsWith('(') && !afterName.startsWith('=') && !afterName.startsWith('function')) continue;
          functions.push({ name: name, line: i + 1 });
          break;
        }
      }
    }
  }
  return functions;
}

function buildIndex() {
  const files = scanFiles(ROOT);
  const grouped = {};

  for (const file of files) {
    const relPath = path.relative(ROOT, file).replace(/\\/g, '/');
    const cat = categorizeFile(relPath);
    if (!grouped[cat]) grouped[cat] = [];
    const funcs = extractFunctions(file);
    if (funcs.length > 0) grouped[cat].push({ relPath, funcs });
  }

  let md = '# Function Index\n\n';
  md += '**Generated**: ' + new Date().toISOString().split('T')[0] + ' | ';
  md += '**Total files**: ' + files.length + ' JS/TS/GS\n\n';

  for (const [cat, entries] of Object.entries(grouped)) {
    md += '## `' + cat + '`\n\n';
    md += '| Line | Function | File |\n|------|----------|------|\n';
    for (const entry of entries) {
      for (const fn of entry.funcs) {
        md += '| ' + fn.line + ' | `' + fn.name + '` | `' + path.basename(entry.relPath) + '` |\n';
      }
    }
    md += '\n';
  }

  md += '---\n';
  md += '> Auto-generated by `tooling/generate-index.js`\n';

  fs.writeFileSync(OUTPUT, md, 'utf8');
  console.log('Index generated: ' + OUTPUT);
  console.log('  ' + files.length + ' files scanned');
}

buildIndex();
