name: Deploy to GitHub Pages Securely

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Secure Config File
        env:
          MY_URL: ${{ secrets.API_URL }}
          MY_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          mkdir -p js/modules
          U=$(echo "$MY_URL" | tr -d '[:space:]')
          T=$(echo "$MY_TOKEN" | tr -d '[:space:]')
          echo "const SUIT_CONFIG = { apiUrl: '$U', apiToken: '$T' };" > js/modules/config.js
        shell: bash

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
